main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.index),
    path('about', views.about),
    path('services', views.services),
    path('images', views.images),
    path('donate', views.donate),
    path('contact', views.contact),
    path('bmember', views.bmember),
]

sarvapalakaya/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as MainUrls


urlpatterns = [
    path('', include(MainUrls)),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class Query(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = PhoneNumberField(null=False, blank=False)
    query = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Commented By {self.name} on {self.created}"

main/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

from main.models import *


class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ('name', 'phone', 'email', 'query')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'value': '+91'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'query': forms.Textarea(attrs={'class': 'form-control'}), }

main/views.py
from django.shortcuts import render
from main.forms import QueryForm
from main.models import *


def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')


def services(request):
    return render(request, 'main/services.html')


def images(request):
    return render(request, 'main/images.html')


def donate(request):
    return render(request, 'main/donate.html')


def contact(request):
    cSubmit = False
    if request.method == "POST":
        form = QueryForm(request.POST)
        if form.is_valid():
            form.save()
            cSubmit = True
        else:
            return render(request, 'main/contact.html', {'form': form, 'errors': form.errors})
    else:
        form = QueryForm()
    return render(request, 'main/contact.html', {'form': form, 'csubmit': cSubmit})


def bmember(request):
    return render(request, 'main/bmember.html')

templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}

<div class="main">
    <h2 class="text-center">Our Aim</h2>
    <p class="m-5">A major objective of Sarva Palakaya Foundation is social welfare work in relation to illiteracy,
        poverty and disease. Our work aims to break the vicious cycle of poverty and social isolation and to restore
        hope for a better future. We believe that every person has the right to access resources and
        opportunities in order to live and develop with dignity and to become an active and contributing
        member of our society.</p>
    <p class="m-5">
        1. It has been set up as a society to extensively work in the area of environmental &, education
        health employment, environment sports culture, media social and awakening to the national
        spirit among the youth and women to India. <br>
        2. The society shall start to provide Free legal and awareness of rights to people at a grass-
        roots level. The society will have it, own web site with chartrooms for counseling, advice
        and discussion Forums. <br>
        3. To work for uplifting the status of women in the society. To work against female
        circumcision and to fight against the victimization of girl /women by anybody in the society
        on female circumcision or any other related issues. <br>
        4. the society will also prepare young people and women to actively join the education
        programs. To educate the people for adoption of the good norms of a good citizenship and
        to inculcate into the people's mind, ideals of national unity.
        5. to open the branches all over the country (India) for the propagation of the objects of the
        Society. the society fight against exploitation, injustice and corruption if found against any
        individual, class, community in the society. <br>
        a) Try to make people aware the importance of primary, secondary & higher education. <br>
        i) To work sincerely for people and humanity. To provide a platform for the exchange of
        ideas on the social, cultural and educational aspects of the society. The society shall build a
        chain to art & theatre, hostels, and study centers, reading rooms for Youth and women in
        various states. <br>
        ii) To educate people on a range of environmental issues. To educate the people for adoption
        of the good norms of a good citizenship and to inculcate into the people's mind, ideals of
        national unity. <br>
        a. To hold seminars, lectures, debates for the propagation of the objects of the society.
        b. To contribute to the social, cultural, medical, sports and educational betterment of the
        members of the society. <br>

        c. To establish charitable homeopathic hospitals, dispensaries all over the country (India) in
        a. Rural areas for the social welfare of the masses in urban slims and rural areas. <br>

        5. The society will encourage art & theatre sports, activity (both in door & outdoor) by conducting
        local, state national and international level tournaments, coaching camps, training and giving
        Awards to outstanding sports men from India. <br>


        6. The society will create a special educational web site which will import education across the
        Entire country and have all information stored that is needed by a student the society will use
        The internet for guidance for various conducting, courses to internet to students.
        <br>
        7. The society will organize seminars, conferences, debates, fairs in any field for betterment to youth
        and women. <br>
        8. The society has a vision for the country’s you to and women, particularly from rural and Tribal
        areas. It wants to Create ideal village as models of modern day living. <br>
        9. The society will conduct not only its own programs in the northeast states it India, but will also
        Actively participate in all government projects. <br>
        10. The society will hold regular health camps for activities like cataracts, a bloom denotation
        Cancer and health check camps, etc. <br>
        11. To popularize its efforts and create awareness about its various activators the society will publish
        its own newsletter/paper . It may also publish magazines/ books etc. on to picks to its Interne. <br>
        12. The society wants to encourage young scientist, writer, singer, artists, actors, musicians, etc. by
        bringing out books, audio – video tapes, CD’s albums etc. <br>
        13. The society wants to prepare young people to serve the aged persons; it also aims to start senior
        citizen homes in various places, and will also carry out other activities for their welfare the good
        to. <br>
        14. The society also plans to run a project to managed by its youth and women member for foreign
        tourist to show them the cultural heritage of India. To propagate the need for tree plantation/
        pollution control and environmental awareness. <br>
        15. The society will also join hands with other similar organizations and extend those financial help
        and it its expertise. To help and generate training programme for self employment of women
        and educated unemployed people and to work for adult education <br>
    </p>
</div>


{% endblock body %}

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>

<body>

    <!-- Sidenav -->
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn text-dark" onclick="closeNav()">&times;</a>
        <a href="/" class="nav-link white font-weight-bold active text-dark m-0">
            Home
        </a>
        <a href="/about" class="nav-link px-3 font-weight-bold activ text-dark">
            About
        </a>
        <a href="/services" class="nav-link px-3 font-weight-bold active text-dark">
            Services
        </a>
        <a href="/services" class="nav-link px-3 font-weight-bold active text-dark">
            Services
        </a>
        <a href="/contact" class="nav-link px-3 font-weight-bold active text-dark">
            Contact
        </a>
        <a href="/bmember" class="nav-link px-3 font-weight-bold active text-dark">
            Board Member
        </a>

    </div>




    <nav class="navbar navbar-expand-lg bg-body-tertiary mx-50">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo (Custom) (2) (Custom).jpg' %}" alt="">
                <strong class="pink">Sarva Palakaya Foundation </strong>
            </a>

            <button class="navbar-toggler collapsed" data-target="#navbarSupportedContent" type="button"
                aria-controls="navbarScroll" onclick="openNav()" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="  collapse navbar-collapse" id="">
                <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item"> <strong>
                            <a href="" class="nav-link white font-weight-bold pink">
                                Home
                            </a></strong>
                    </li>
                    <li class="nav-item"><strong>
                            <a href="/about" class="nav-link px-3 font-weight-bold pink">
                                About
                            </a></strong>
                    </li>
                    <li class="nav-item"><strong>
                            <a href="/services" class="nav-link px-3 font-weight-bold pink">
                                Services
                            </a></strong>
                    </li>
                    <!-- <li class="nav-item">
                        <a href="/donate" class="nav-link px-3 font-weight-bold active pink">
                            Donate
                        </a>
                    </li> -->
                    <li class="nav-item"><strong>
                            <a href="/contact" class="nav-link px-3 font-weight-bold pink">
                                Contact
                            </a></strong>
                    </li>
                    <li class="nav-item"><strong>
                            <a href="/bmember" class="nav-link px-3 font-weight-bold pink">
                                Board Member
                            </a></strong>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <style>
        html {
            height: 100%;
        }

        .pink {
            color: fuchsia !important;
        }

        .ml-auto {
            margin-left: auto;
        }

        .insta {
            color: rgb(231, 7, 194);
        }

        .yt {
            color: rgb(243, 25, 36);
        }

        .li {
            color: rgb(34, 61, 236);
        }

        .navbar-dark {
            color: white !important;
            border-bottom: 0.5px solid white;
        }

        .navbar-light {
            color: black !important;
            border-bottom: 0.5px solid black;
            background-color: white;
        }

        .white {
            color: white;
            margin: 0px 0px 0px 50px;
        }

        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 10;
            top: 0;
            left: 0;
            background-color: #f479f0dc;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

        .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #111;
            color: white;
            padding: 10px 15px;
            border: none;
        }

        .openbtn:hover {
            background-color: #444;
        }

        #main {
            transition: margin-left .5s;
            padding: 20px;
        }

        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }

        .element {
            position: -webkit-sticky;
            position: sticky;
            top: 50%;
            width: 40px;
            background-color: #f479f0dc;
            padding: 3px;
            justify-content: center;
            font-size: 10px;
            float: right;
            border-radius: 5px;

        }
    </style>

    <script>
        /* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
    <div class="element">

        <a href="https://www.instagram.com/p/CsMmuTphgG7/?utm_source=ig_web_copy_link&igshid=MmJiY2I4NDBkZg=="
            class="insta" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-instagram"
                viewBox="0 0 16 16">
                <path
                    d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
            </svg>
        </a>

        <a href="https://www.facebook.com/profile.php?id=100083213078300&mibextid=ZbWKwL" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-facebook"
                viewBox="0 0 16 16">
                <path
                    d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
            </svg> </a>


        <a href="https://youtube.com/@SarvaPalakayaFoundation" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-youtube yt"
                viewBox="0 0 16 16">
                <path
                    d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
            </svg> </a>

        <a href="http://linkedin.com/in/sarva-palakaya-foundation-5aab15271" target="_blank">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-linkedin li"
                viewBox="0 0 16 16">
                <path
                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
            </svg> </a>


    </div>
    {% block body %}

    {% endblock body %}

</body>

</html>

templates/main/bmember.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}

<div class="text-center">

    <img src="{% static 'images/members.jpg' %}" style="width: 90%;" class="" alt="">
</div>


{% endblock body %}

templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}

{% if csubmit %}
<h2 class="text-danger mb-5">👏Your Query will se solved at the earliest... </h2>
{% else %}

<form action="" method="post" class="p-3 m-2 rounded"> {% csrf_token %}
    <h5 class="flexend pl-5"> <strong>Tell us query : </strong> </h5>
    <div class="text-danger">
        {% if errors %}
        {{ errors }}
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="id_name" class="">Name :</label><br>{{form.name}}
    </div>

    <div class="mb-3">
        <label for="id_phone" class="form-label">Phone Number</label>
        <br>{{form.phone}}
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email address</label>
        <br>{{form.email}}
    </div>
    <div class="mb-3">
        <label for="id_query" class="form-label">Your Query</label>
        <br>{{form.query}}
    </div>

    <button type="submit" class="btn btn-primary ml-auto">Submit</button>


</form>
{% endif %}

<h3 class="ml-5">Our Locations :</h3>
<div class="addresses m-3">

    <div class="card" style="width: 18rem; margin:5px;">
        <div class="card-body">
            <h5 class="card-title">Head Office</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Lucknow(Uttar Pradesh)</h6>
            <p class="card-text">H.No 592-CHHA/672/15, New swaroop Nagar Kharika Telibagh, Lucknow up.</p>
        </div>
    </div>

    <div class="card" style="width: 18rem; margin:5px;">
        <div class="card-body">
            <h5 class="card-title">Regional Branch</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Ranchi(Jharkhand)</h6>
            <p class="card-text">Pilger lane, PO- Church road, Ranchi Jharkhand 834001</p>
        </div>
    </div>

    <div class="card" style="width: 18rem; margin:5px;">
        <div class="card-body">
            <h5 class="card-title">Regional Branch</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">kichha(Uttarakhand) </h6>
            <p class="card-text">addr-H.no-324,Ward no-8,behind teshil and pant coloney kichha (udham.singh.nagar)
                uttrakhand 263148.</p>
        </div>
    </div>

    <div class="card" style="width: 18rem; margin:5px;">
        <div class="card-body">
            <h5 class="card-title">Or</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Mail us at : </h6>
            <p class="card-text"><a class="ml-5"
                    href="mailto:sarvapalakayafoundation@gmail.com">sarvapalakayafoundation@gmail.com</a></p>
        </div>
    </div>

    <div class="card" style="width: 18rem; margin:5px;">
        <div class="card-body">
            <h5 class="card-title">And</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">Follow us at : </h6>




        </div>
    </div>
</div>

<style>
    .bi {
        margin: 5px;
    }



    .flexend {
        align-items: flex-end;
    }

    .ml-5 {
        margin-left: 5px;
    }

    .card,
    form {
        background-color: rgba(238, 147, 233, 0.645);
    }

    .addresses {
        display: flex;
        flex-wrap: wrap;
    }
</style>


{% endblock body %}

templates/main/donate.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}


{% endblock body %}

templates/main/images.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}


{% endblock body %}

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}

{% block body %}

<div id="carouselExampleCaptions" class="carousel slide m-1">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'images/1.jpg' %}" class="d-block w-100" alt="...">
            <!-- <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Some representative placeholder content for the first slide.</p>
            </div> -->
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/3.jpg' %}" class="d-block w-100" alt="...">
            <!-- <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Some representative placeholder content for the second slide.</p>
            </div> -->
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/6.jpg' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Some representative placeholder content for the third slide.</p>
            </div>
        </div>

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<style>
    form {
        margin-top: 56px !important;
    }
</style>


{% endblock body %}

templates/main/services.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
sarva palakaya Foundation
{% endblock %}


{% block body %}

<div class="main m-5">
    <p>1- Feed for needy people</p>
    <p>2- Vidya: A caring hand</p>

    <div class="images">
        <img src="{% static 'images/1.jpg' %}" class="img-thumbnail" alt="...">
        <img src="{% static 'images/3.jpg' %}" class="img-thumbnail" alt="...">
        <img src="{% static 'images/4.jpg' %}" class="img-thumbnail" alt="...">
        <img src="{% static 'images/5.jpg' %}" class="img-thumbnail" alt="...">
        <img src="{% static 'images/6.jpg' %}" class="img-thumbnail" alt="...">
    </div>


</div>
<style>
    .img-thumbnail {
        max-width: 300px;
        margin: 6px;

    }

    .images {
        display: flex;
        flex-wrap: wrap;
    }
</style>


{% endblock body %}